	,"DEBPKG:debian/cpan_definstalldirs - Provide a sensible INSTALLDIRS default for modules installed from CPAN."
	,"DEBPKG:debian/db_file_ver - https://bugs.debian.org/340047 Remove overly restrictive DB_File version check."
	,"DEBPKG:debian/doc_info - Replace generic man(1) instructions with Debian-specific information."
	,"DEBPKG:debian/enc2xs_inc - https://bugs.debian.org/290336 Tweak enc2xs to follow symlinks and ignore missing @INC directories."
	,"DEBPKG:debian/errno_ver - https://bugs.debian.org/343351 Remove Errno version check due to upgrade problems with long-running processes."
	,"DEBPKG:debian/libperl_embed_doc - https://bugs.debian.org/186778 Note that libperl-dev package is required for embedded linking"
	,"DEBPKG:fixes/respect_umask - Respect umask during installation"
	,"DEBPKG:debian/writable_site_dirs - Set umask approproately for site install directories"
	,"DEBPKG:debian/extutils_set_libperl_path - EU:MM: set location of libperl.a under /usr/lib"
	,"DEBPKG:debian/no_packlist_perllocal - Don't install .packlist or perllocal.pod for perl or vendor"
	,"DEBPKG:debian/fakeroot - Postpone LD_LIBRARY_PATH evaluation to the binary targets."
	,"DEBPKG:debian/instmodsh_doc - Debian policy doesn't install .packlist files for core or vendor."
	,"DEBPKG:debian/ld_run_path - Remove standard libs from LD_RUN_PATH as per Debian policy."
	,"DEBPKG:debian/libnet_config_path - Set location of libnet.cfg to /etc/perl/Net as /usr may not be writable."
	,"DEBPKG:debian/perlivp - https://bugs.debian.org/510895 Make perlivp skip include directories in /usr/local"
	,"DEBPKG:debian/squelch-locale-warnings - https://bugs.debian.org/508764 Squelch locale warnings in Debian package maintainer scripts"
	,"DEBPKG:debian/patchlevel - https://bugs.debian.org/567489 List packaged patches for 5.40.1-6+deb13u1 in patchlevel.h"
	,"DEBPKG:fixes/document_makemaker_ccflags - https://bugs.debian.org/628522 [rt.cpan.org #68613] Document that CCFLAGS should include $Config{ccflags}"
	,"DEBPKG:debian/find_html2text - https://bugs.debian.org/640479 Configure CPAN::Distribution with correct name of html2text"
	,"DEBPKG:debian/perl5db-x-terminal-emulator.patch - https://bugs.debian.org/668490 Invoke x-terminal-emulator rather than xterm in perl5db.pl"
	,"DEBPKG:debian/cpan-missing-site-dirs - https://bugs.debian.org/688842 Fix CPAN::FirstTime defaults with nonexisting site dirs if a parent is writable"
	,"DEBPKG:debian/makemaker-pasthru - https://bugs.debian.org/758471 Pass LD settings through to subdirectories"
	,"DEBPKG:debian/makemaker-manext - https://bugs.debian.org/247370 Make EU::MakeMaker honour MANnEXT settings in generated manpage headers"
	,"DEBPKG:debian/kfreebsd-softupdates - https://bugs.debian.org/796798 Work around Debian Bug#796798"
	,"DEBPKG:debian/hurd-softupdates - https://bugs.debian.org/822735 Fix t/op/stat.t failures on hurd"
	,"DEBPKG:fixes/math_complex_doc_great_circle - https://bugs.debian.org/697567 [rt.cpan.org #114104] Math::Trig: clarify definition of great_circle_midpoint"
	,"DEBPKG:fixes/math_complex_doc_angle_units - https://bugs.debian.org/731505 [rt.cpan.org #114106] Math::Trig: document angle units"
	,"DEBPKG:fixes/cpan_web_link - https://bugs.debian.org/367291 CPAN: Add link to main CPAN web site"
	,"DEBPKG:debian/installman-utf8 - https://bugs.debian.org/840211 Generate man pages with UTF-8 characters"
	,"DEBPKG:debian/perldoc-pager - https://bugs.debian.org/870340 [rt.cpan.org #120229] Fix perldoc terminal escapes when sensible-pager is less"
	,"DEBPKG:debian/prune_libs - https://bugs.debian.org/128355 Prune the list of libraries wanted to what we actually need."
	,"DEBPKG:debian/mod_paths - Tweak @INC ordering for Debian"
	,"DEBPKG:debian/deprecate-with-apt - https://bugs.debian.org/747628 Point users to Debian packages of deprecated core modules"
	,"DEBPKG:debian/perlbug-editor - https://bugs.debian.org/922609 Use \"editor\" as the default perlbug editor, as per Debian policy"
	,"DEBPKG:debian/eu-mm-perl-base - https://bugs.debian.org/962138 Suppress an ExtUtils::MakeMaker warning about our non-default @INC"
	,"DEBPKG:fixes/io_socket_ip_ipv6 - Disable getaddrinfo(3) AI_ADDRCONFIG for localhost and IPv4 numeric addresses"
	,"DEBPKG:debian/usrmerge-lib64 - https://bugs.debian.org/914128 Configure / libpth.U: Do not adjust glibpth when /usr/lib64 is present."
	,"DEBPKG:debian/usrmerge-realpath - https://bugs.debian.org/914128 Configure / libpth.U: use realpath --no-symlinks on Debian"
	,"DEBPKG:fixes/x32-io-msg-skip - https://bugs.debian.org/922609 Skip io/msg.t on x32 due to broken System V message queues"
	,"DEBPKG:debian/configure-regen - https://bugs.debian.org/762638 Regenerate Configure et al. after probe unit changes"
	,"DEBPKG:fixes/json-pp-options - https://bugs.debian.org/1078058 Fix json_pp option handling"
	,"DEBPKG:fixes/test-harness-bailout - https://bugs.debian.org/1078060 Prevent double summary on bail-out"
	,"DEBPKG:fixes/CVE-2024-56406 - CVE-2024-56406: Heap-buffer-overflow with tr//"
	,"DEBPKG:fixes/CVE-2025-40909-metaconfig - https://bugs.debian.org/1098226 [GH #23010] Check for fdopendir"
	,"DEBPKG:fixes/CVE-2025-40909-1 - https://bugs.debian.org/1098226 [GH #23010] [84be063] CVE-2025-40909: Clone dirhandles without fchdir"
	,"DEBPKG:fixes/CVE-2025-40909-2 - https://bugs.debian.org/1098226 [GH #23010] [b088e97] Minor corrections to 1f9097b342e0e37d619dfab6ea82ea99611b30bf"
	,"DEBPKG:fixes/CVE-2025-40909-3 - https://bugs.debian.org/1098226 [GH #23010] [08dffa0] Use PerlLIO_dup_cloexec in Perl_dirp_dup to set O_CLOEXEC"
	,"DEBPKG:fixes/CVE-2025-40909-metaconfig-reorder - Slightly reorder Configure and config_h.SH to match metaconfig output"
	,"DEBPKG:fixes/CVE-2026-8376-tests - https://bugs.debian.org/1137345 [e842efd] perl/perl-security#147: test cases"
	,"DEBPKG:fixes/CVE-2026-8376 - https://bugs.debian.org/1137345 [5e7f119] perl/perl-security#147: test against the actual character lengths"
	,"DEBPKG:fixes/CVE-2026-57432-1 - https://bugs.debian.org/1138905 [GH #24445] [5f7eb6b] pp_pack.c: Avoid ssize_t overflow when calculating the size of a structure"
	,"DEBPKG:fixes/CVE-2026-57432-2 - https://bugs.debian.org/1138905 [GH #24445] [40754ed] pp_pack.c: Avoid some other potential overflows when calculating sizes"
	,"DEBPKG:fixes/CVE-2026-57433 - https://bugs.debian.org/1138906 [e4f6817] Storable.xs: Avoid signed int overflow when unpacking a list of hook data items"
	,"DEBPKG:fixes/CVE-2026-7010 - https://bugs.debian.org/1138858 CVE-2026-7010: fix for request / header smuggling"
	,"DEBPKG:fixes/CVE-2026-7010-tests - https://bugs.debian.org/1138858 CVE-2026-7010: add tests"
	,"DEBPKG:fixes/CVE-2025-15649 - https://bugs.debian.org/1138863 Enhance _dosToUnixTime to handle zero and invalid datetime values; add tests for edge cases. Fixes #65"
	,"DEBPKG:fixes/CVE-2025-15649-tests - https://bugs.debian.org/1138863 Add tests for handling zero and invalid datetime values in unzip functionality. Fix for #65"
	,"DEBPKG:fixes/CVE-2026-48959 - https://bugs.debian.org/1138856 Fix typo in fastForward #72"
	,"DEBPKG:fixes/CVE-2026-48961 - https://bugs.debian.org/1138855 fix: correct unpackValueQ -> unpackValue_Q typo in decodeLitteEndian"
	,"DEBPKG:fixes/CVE-2026-48962 - https://bugs.debian.org/1138854 remove use of eval in globmapper. #73"
	,"DEBPKG:fixes/CVE-2026-7017-1 - https://bugs.debian.org/1140152 refuse https to http redirects by default"
	,"DEBPKG:fixes/CVE-2026-7017-2 - https://bugs.debian.org/1140152 strip auth headers on cross-origin redirects"
	,"DEBPKG:fixes/CVE-2026-7017-3 - https://bugs.debian.org/1140152 Fix protocol-relative Location handling so it can't be used to bypass credential strip"
	,"DEBPKG:fixes/CVE-2026-7017-4 - https://bugs.debian.org/1140152 demonstrate that https upgrade now strips credentials"
	,"DEBPKG:fixes/CVE-2026-7017-5 - https://bugs.debian.org/1140152 Add tests to cover redirects from requests providing basic auth via the URL"
	,"DEBPKG:fixes/CVE-2026-42496-1 - https://bugs.debian.org/1138860 https://bugs.debian.org/1138859 Validate symlink and hardlink linkname in SECURE MODE"
	,"DEBPKG:fixes/CVE-2026-42496-2 - https://bugs.debian.org/1138860 https://bugs.debian.org/1138859 Allow `..` links in secure extract in parent path"
	,"DEBPKG:fixes/CVE-2026-13221 - [620e07a] https://bugs.debian.org/1142037 [GH #23388] regcomp_study: Don't create a trie that would overflow"
	,"DEBPKG:fixes/CVE-2026-19487 - https://bugs.debian.org/1144668 [GH #22892] [1a21aba] regexec.c - Fix GH 22892 - AHO-CORASICK edge case issue"
	,"DEBPKG:fixes/CVE-2026-12087 - https://bugs.debian.org/1140152 [de19a0b] cpan/Socket - Update to version 2.041"
