#!/bin/sh

set -e

PREREQ="fuse"

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/ntfs-3g /usr/bin

ln -s /usr/bin/ntfs-3g "${DESTDIR}/usr/sbin/mount.ntfs-3g"
ln -s /usr/bin/ntfs-3g "${DESTDIR}/usr/sbin/mount.ntfs"

exit 0
